CREATE DATABASE IF NOT EXISTS blog_db;

USE blog_db;

CREATE TABLE IF NOT EXISTS blogs (
  id VARCHAR(50) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  excerpt TEXT NOT NULL,
  coverImage VARCHAR(500) NOT NULL DEFAULT '',
  published TINYINT(1) NOT NULL DEFAULT 0,
  createdAt VARCHAR(50) NOT NULL,
  updatedAt VARCHAR(50) NOT NULL,
  blocks JSON NOT NULL
);
